### PR TITLE
added font awesome cdn and test element

### PR DESCRIPTION
**Pull request by AlvisonHunterArnuero**
**Hello Team**

This PR adds  font awesome cdn and test elements to the main files in order to use this library. Please check it out whenever you have a chance. Thanks, Team!

### CODE REVIEW

**Comment by Ralexs0096** [comment]
TL;DR!

**Review by Jean-Cairoli — APPROVED** [review]
Great Work!

**Review by Ralexs0096 — APPROVED** [review]
Everything is fine! Cool! good job!

**Review by joabto87 — APPROVED** [review]
Awesome!

**Pull request merged**
